version: '2.3'

services:

  cuda:
    image: image-renderer
    build: 
      context: ../
      dockerfile: docker/gpu/Dockerfile
    container_name: image_renderer
    runtime: nvidia
    restart: always
    volumes:
      - ../gpu:/gpu
    environment:
      - NVIDIA_VISIBLE_DEVICES=all

  expressjs:
    image: middleware
    build:
      context: ../
      dockerfile: docker/server/Dockerfile
    container_name: middleware
    volumes:
      - ../server:/server
    restart: always
    links:
      - cuda
    ports: 
      - 8083:80
    working_dir: /server

  react:
    image: frontend
    build:
      context: ../
      dockerfile: docker/app/Dockerfile
    container_name: front-end
    volumes:
      - ../app:/app
    restart: always
    ports:
      - 80:3000
    links:
      - expressjs
    working_dir: /app
  



  