version: '2.3'

services:

  cuda:
    image: image-renderer
    build: 
      context: ../
      dockerfile: docker/gpu/Dockerfile
    container_name: image_renderer
    runtime: nvidia
    restart: always
    volumes:
      - ../gpu:/gpu
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    networks:
      app_net:
        ipv4_address: 172.19.1.2

  expressjs:
    image: middleware
    build:
      context: ../
      dockerfile: docker/server/Dockerfile
    container_name: middleware
    volumes:
      - ../server:/server
    restart: always
    links:
      - cuda
    ports: 
      - 8083:80
    working_dir: /server
    networks:
      app_net:
        ipv4_address: 172.19.1.3

  react:
    image: frontend
    build:
      context: ../
      dockerfile: docker/app/Dockerfile
    container_name: front-end
    volumes:
      - ../app:/app
    restart: always
    ports:
      - 80:3000
    links:
      - expressjs
    working_dir: /app
    networks:
      app_net:
        ipv4_address: 172.19.1.4

networks:
  app_net:
    ipam:
      driver: default
      config:
        - subnet: "172.19.1.0/24"
        - subnet: "2001:3984:3989::/64"
  



  